export const ImageApi = [
    "./Image/img1.jpeg",
    "./Image/img2.jpeg",
    "./Image/img3.jpeg",
    "./Image/img4.jpeg",
    "./Image/img5.jpeg",
    "./Image/img6.jpeg",
    "./Image/img7.jpeg",
    "./Image/img8.jpeg",
    "./Image/img9.jpeg",
    "./Image/img10.jpeg",
    "./Image/img11.jpeg",
    "./Image/img13.jpeg",
    "./Image/img14.jpeg",
    "./Image/img15.jpeg",
    "./Image/img16.jpeg",
];